### ISSUE TITLE
Dapr dashboard does not respect the global registry value

### ISSUE THREAD

**Issue by aytekinar** [dapr/helm-charts#14]
### Current Behavior

I am using version `1.4.3` of `dapr/dapr`, and I have noticed that the Dapr dashboard char does not respect the global registry value in `values.yaml`.

### Desired Behavior

Similar to, e.g., `dapr-sentry`, `dapr-dashboard` should also pick the `global.registry` value from `values.yaml`.

### Possible Fix

The current deployment template (for `dapr-dashboard`) reads as below:

```yaml
      - name: dapr-dashboard
        image: "{{ .Values.image.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.global.imagePullPolicy }}
```

Perhaps, it should read instead (cheating from `dapr-sentry`'s deployment template):

```yaml
{{- if contains "/" .Values.image.name }}
        image: "{{ .Values.image.name }}"
{{- else }}
        image: "{{ .Values.global.registry }}/{{ .Values.image.name }}:{{ .Values.image.tag }}"
{{- end }}
```

Cc: @baboune
